### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by elisee** [stevedonovan/MonoLuaInterface#1]
Hey there,

Have you decided on a license for MonoLuaInterface? If so could you add it to the repository so that it's official?

Thanks!

**Comment by stevedonovan** [comment]
Sorry Elisee, my bad. It is an MIT licence, like LuaInterface. I'll put up a licence file.

**Comment by elisee** [comment]
Thank you very much! :)

I'll be using a (modified) version of MonoLuaInterface to get CraftStudio (the real-time cooperative game-making platform I'm working on) to run on Linux and OS X. I call my variant MonoBoxedLua and you can check it out at https://bitbucket.org/sparklinlabs/monoboxedlua/ (also under the MIT license)
